var details = [
  [['Atlantic Rock Crab',
    'https://iili.io/Bylj2a.md.jpg',
    'Atlantic rock crabs are found in the Atlantic Ocean along the East Coast, and live in a wide range of water depths.',
    'They can be found in shallow water and incoming tides, but are also in water as deep as 2,600 feet.',
    'The Atlantic rock crab has a wide oval yellow shell with specks of brown and red.',
    ],
   ['Gulf Stone Crab',
    'https://iili.io/BylwYJ.md.jpg',
    'The gulf stone crab grows to 3.5 inches long and 4 inches wide and is brownish red in color with gray spots and a tan underside.',
    'Gulf stone crabs prefer a diet of mollusks and shellfish such as oysters, but will eat sea grass and decaying flesh of dead animals.',
    'They are found around the Gulf Coast in bays and reefs where they can more easily avoid their predators, such as sea turtles and fish like grouper.',
    ],
   ['Blue Crab',
    'https://iili.io/BylNkv.md.jpg',
    'Blue crabs are one of the most popular with commercial and recreational fisherman because of their sweeter meat.',
    'They have bright blue claws, often with orange tips, and can be found walking sideways rather than towards the front most of the time.',
    'The male blue crab will carry the female after she has molted and they have mated. This is to protect her, and will continue until her shell is completely hardened.',
    ]],

  [['Avocets',
    'https://iili.io/BylkIp.md.jpg',
    'Avocets are relatively large wading shorebirds with small heads, very thin, sharply upturned bills, and exceptionally long, thin legs.',
    'There are only four species of avocet, and because there are so few, they are often target birds for birders who travel extensively.',
    'The black-and-white pied avocet is found in Africa, Europe, and Asia, the red-necked avocet is found in Australia.',
    ],
   ['Shorebirds',
    'https://iili.io/BylvhN.md.jpg',
    'Shorebirds come in many shapes and sizes, but all of them share certain physical and behavioral traits.',
    'Nearly all shorebirds have a distinct preference for wet habitats and shorelines, both on coasts as well as along inland waterways, marshes, or general riparian habitats.',
    'Most shorebirds are carnivorous and eat a range of insects, mollusks, crustaceans, worms, larvae, tadpoles, and similar prey.',
   ],
   ['Sandpipers',
    'https://iili.io/Byl8QI.md.jpg',
    'The most diverse category of shorebirds is the sandpipers. Sizes and colorations range greatly from tiny, bland birds to much larger, distinctly marked species.',
    'All of these birds have sensitive bills they use to probe through the sand or dirt when feeding, and they often eat insects, worms, mollusks, and similar prey.',
    'While there are many species that include “sandpiper” in their name, other species such as turnstones, stints, godwits, curlews, woodcocks, phalaropes, yellowlegs, snipes, and dowitchers are also classified as sandpipers.',
   ]],

   [['Capricon Octopus',
    'https://iili.io/BylgEX.md.webp',
    'The Capricorn Octopus gets its name from the shape its arms tend to form around its body. They are smaller octopuses.',
    'Capricorn octopuses are nocturnal, only coming out at night to forage for their food.',
    'They come out of their caves and crevices into Australia’s dark waters so that they have less competition than they would during the day.',
    ],
   ['Greater Blue-Ringed Octopus',
    'https://iili.io/BylPYG.md.webp',
    'These beautiful octopuses have blue rings dotted all over a yellow to orange body, each of which is highly venomous.',
    'The Greater Blue-Ringed octopus is thought to be the most toxic of any of the world’s marine animals. The rings seemingly glow when the octopus is angry,',
    'Instead of manufacturing ink, this species creates a poison mixed with tetrodotoxin, just as the poisonous pufferfish is.',
   ],
   ['Algae Octopus',
    'https://iili.io/BylQTl.md.webp',
    'The Algae Octopus gets its nickname from the camouflaged form while hiding or on the hunt.',
    'It resembles a shell of a gastropod that has been overgrown with algae, staying still on the ocean floor for hours at a time.',
    'These octopuses are tiny. Their hands are about the size of a clementine with legs about 10 inches (25.4 cm) long.',
   ]],
  
  [['Common starfish',
    'https://iili.io/By0dyx.md.jpg',
    'The common starfish normally has five arms, broad at their base and gradually tapering to a point at their tips.',
    ' There is a line of short white spines running along the centre of the aboral (upper) surface of the arms with low, soft mounds.',
    'The common starfish is usually orange or brownish in color, and sometimes violet; specimens found in deeper waters are pale.',
    ],
   ['Choriaster Starfish',
    'https://iili.io/By03TQ.md.jpg',
    'The adorable Choriaster or Doughboy Starfish as it is affectionately known, found in East Africa, the Indo-Pacific and Papua New Guinea.',
    'The recognisable characteristics of the Doughboy is cute rounded bodies and five stubby arms.',
    'One of the most intriguing starfish traits is that they have a fully retractable stomach.',
    ],
   ['Necklace Starfish',
    'https://iili.io/By0FjV.md.jpg',
    'Their starfish characteristics include an intricate marbled body, covered in eye-catching dots in all shapes and sizes.',
    'The tips of their arms are usually a vibrant red colour which enables them to ward off prey.',
    'The Necklace Starfish live in depths of up to 50 meters in the tropical waters of the Indian Ocean and Western Pacific.',
    ]],

    [['Calm',
    'https://iili.io/By0BG1.md.jpg',
    'Clams have two shells of equal size connected by two adductor muscles and have a powerful burrowing foot',
    'They live in both freshwater and marine environments; in salt water they prefer to burrow down into the mud',
    'Many edible clams such as palourde clams are oval or triangular;[5] however, razor clams have an elongated parallel-sided shell.',
    ],
   ['Cockle',
    'https://iili.io/By0qCP.md.jpg',
    'The shell is oval, and covered by ribs, which are flattened in the middle part of the shell.',
    'The ribbed oval shells can reach 6 centimetres (2.4 in) across and are white, yellowish or brown in colour.',
    'The common cockle is harvested commercially and eaten in much of its range.',
    ],
   ['Turritella',
    'https://iili.io/By0C6F.md.jpg',
    'They have tightly coiled shells, whose overall shape is basically that of an elongated cone.',
    'This beautiful and slim shell is very common, but they are not often found intact.',
    'The name Turritella comes from the Latin word turritus meaning "turreted" or "towered" and the diminutive suffix -ella.',
    ]],

    // Dolphins
    [['Spinner Dolphin',
    'https://iili.io/C9Sus9.md.jpg',
    'Spinner dolphins also have very long beaks and exhibit different shades of gray, from dark on the top to a clearer belly.',
    'They can jump up to 10 feet (3 m) out of the water and do multiple spins before landing.',
    ' They live in tropical, subtropical and temperate areas of the Pacific Ocean, the Indian Ocean, and the Atlantic Ocean.',
    ],
   ['Pacific White-Sided Dolphin',
    'https://iili.io/C9SRfe.md.jpg',
    'They have a creamy belly and throat, a dark gray back and lighter gray patterns on the side.',
    'They’re a very active and inquisitive species, often approaching boats and pods usually number around 100 individuals.',
    'Although not as popular as bottlenose dolphins, this species is also commonly kept in captivity.',
    ],
   ['Atlantic Bottlenose Dolphin',
    'https://iili.io/C9SaJj.md.jpg',
    'The bottlenose dolphin is one of the most famous species, beginning with the television show “Flipper.”',
    'Bottlenose dolphins live in areas from tropical to temperate waters in pods of 10 to 30 individuals.',
    'Their high intelligence and curiosity toward humans makes them most popular species for marine parks and aquariums.',
    ]],

    // turtles
    [['Green Turtle',
    'https://www.conserveturtles.org/wp-content/uploads/GreenTurtle-RalphPace.jpg',
    'Green turtles are found mainly in tropical and subtropical waters.'
    'Green turtles are in fact named for the greenish color of their cartilage and fat, not their shells.',
    'They migrate long distances between feeding grounds and the beaches from where they hatched.',
    ],
   ['Leatherback ',
    'https://www.conserveturtles.org/wp-content/uploads/leatherback-pic.jpg',
    'It is champion of sea turtles: It grows the largest, dives the deepest, travels the farthest of all sea turtles.',
    'It is the largest of all living turtles and the heaviest non-crocodilian reptile.',
    'Its carapace is covered by oily flesh and flexible, leather-like skin, for which it is named.',
    ],
   ['Loggerhead',
    'https://www.conserveturtles.org/wp-content/uploads/JuvenileLoggerhead-JimAngy.jpg',
    'The loggerhead sea turtle is found in the Atlantic, Pacific, and Indian Oceans, as well as the Mediterranean Sea.',
    'The skin ranges from yellow to brown in color, and the shell is typically reddish brown.',
    'The loggerhead sea turtle is omnivorous, feeding mainly on bottom-dwelling invertebrates.',
    ]],

    // Boats
    [['Bowrider Boats',
    'https://www.extraspace.com/blog/wp-content/uploads/2018/05/which-boat-is-right-for-you-bowrider-boats.jpg',
    'Named for its expansive bow area, bowriders are considered as the most popular of power boats for families.',
    'Ample seating is available behind the cockpit area, which can protect you from spray.',
    'The V-shaped design of the bottom is great for easily navigating through different water conditions.',
    ],
   ['Dinghys',
    'https://www.extraspace.com/blog/wp-content/uploads/2018/05/which-boat-is-right-for-you-dinghys.jpg',
    'Dinghys are small vessels that act as helpers to larger boats that may not be able to navigate tight areas',
    'The flat bottom allows easy movement through shallow waters without becoming stuck.',
    'Some are equipped with outboard motors, while others rely on paddles for power.',
    ],
   ['Bass Boats',
    'https://www.extraspace.com/blog/wp-content/uploads/2018/05/which-boat-is-right-for-you-bass-boats.jpg',
    'Bass boats are the perfect type of fishing boats for those with one goal in mind snaring largemouth bass.',
    'With easily operated, high-horsepower trolling motors, these small boats are perfect for first-time owners.',
    'These boats also include built-in storage for fishing tackle and floor space for fishing chairs.',
    ]],

    // Sandcastles
    [['The Ulitmate Sand Castle',
    'https://cms.hostelbookers.com/hbblog/wp-content/uploads/sites/3/2011/09/Sand-castle-castle.jpg',
    'The mother of all sandcastles.',
    'This beauty makes any bucket and spade effort look obsolete.',
    'Thanks Eric Kilby.',
    ],
   ['The Man Holding a Sand Brain',
    'https://iili.io/C9SGWP.md.jpg',
    'This bizarre creation was displayed at the Orange County Fair in California.',
    'You’ll find everything from sand sports super show where sand artists display their amazing work in the hopes of winning some cool prizes',
    'Thanks vmiramontes.',
    ],
   ['The Simpsons in the Sand',
    'https://iili.io/C9SEzB.md.jpg',
    'The question is, how did they make that fire?',
    'Thanks edeidin.',
    'Thanks',
    ]],

    // Lighthouse
    [['Aguada Lighthouse',
    'https://iili.io/C9SOeR.md.webp',
    'It was built by the Portuguese as a protection against the Dutch and the Marathas.',
    'It is located in Candolim and was a very important lighthouse for Goa during those times. ',
    'The lighthouse with the fort, and the beautiful environment, it is a fantastic place of interest.',
    ],
   ['Kaup Lighthouse',
    'https://iili.io/C9Sebp.md.jpg',
    'Kaup is a small village located near Udupi in Karnataka, and the lighthouse is a star attraction here.',
    'The beach is on the shores of the Arabian Sea, and the lighthouse was built in the year 1901.',
    'It is open for visitors and offers amazing views of the sea and the surrounding areas.',
    ],
   ['Manapad Lighthouse',
    'https://im.whatshot.in/img/2020/Sep/24940573-1600834216.jpg',
    'The beautiful Manapad Beach is home to this lighthouse and is a very popular attraction.',
    'The beach is known to be one of the most important historical beaches in India.',
    'It is the spot where the picturesque Holy Cross Church is located, and right beside it is the lighthouse in red and white',
    ]],

    // Beaches
    [['Radhanagar Beach, Havelock Island',
    'https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2015/07/Radhanagar-Beach-Havelock-Island.jpg',
    'In the year 2007, Time’s Magazine ranked Radhanagar Beach as Asia’s best and 7th in the world.',
    'Many people across the world come over to marvel at this lovely beach.',
    'So, it’s needless to say that it is the best beach in India.',
    ],
   ['Ross and Smith Island Beach',
    'https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2015/07/Ross-and-Smith-Island-Beach-in-Andaman.jpg',
    'The twin islands of Ross and Smith are connected by a narrow sandbank of glittering white sand.',
    'It is definitely one of the top beaches in India that offers incredible swimming and snorkeling experience in Andaman.',
    'Also known as Twin Islands of the Andaman',
    ],
   ['Wandoor Beach, Port Blair',
    'https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2015/07/Wandoor-Beach-in-Andaman.jpg',
    'Wandoor Beach is a famous tourist spot in the Andaman Islands, situated in Port Blair.',
    'It spread over a vast area and is usually frequented by a lot of tourists and is one of the best beaches in India for honeymoon.',
    'If long walks on the beach are what you’re looking for, this is just the place.',
    ]],

              ]
